import type { Worker } from './types';

export const workers: Worker[] = [
  {
    id: '1',
    name: 'Ramesh Kumar',
    skill: 'Plumber',
    rate: 800,
    avatar: 'https://placehold.co/400x400.png',
    description: '10+ years of experience in residential and commercial plumbing. Quick and reliable service.',
    rating: 4.8,
    jobsCompleted: 150,
  },
  {
    id: '2',
    name: 'Suresh Singh',
    skill: 'Electrician',
    rate: 900,
    avatar: 'https://placehold.co/400x400.png',
    description: 'Certified electrician for all your wiring, fixture installation, and repair needs. Safety first.',
    rating: 4.9,
    jobsCompleted: 210,
  },
  {
    id: '3',
    name: 'Deepak Verma',
    skill: 'Carpenter',
    rate: 1000,
    avatar: 'https://placehold.co/400x400.png',
    description: 'Skilled in furniture making, repairs, and custom woodwork. Precision and quality craftsmanship.',
    rating: 4.7,
    jobsCompleted: 120,
  },
  {
    id: '4',
    name: 'Manoj Sharma',
    skill: 'Painter',
    rate: 750,
    avatar: 'https://placehold.co/400x400.png',
    description: 'Professional painter for interior and exterior projects. Clean work and beautiful finishes.',
    rating: 4.8,
    jobsCompleted: 185,
  },
  {
    id: '5',
    name: 'Amit Patel',
    skill: 'Mason',
    rate: 950,
    avatar: 'https://placehold.co/400x400.png',
    description: 'Expert in brickwork, plastering, and concrete jobs. Strong and durable construction work.',
    rating: 4.6,
    jobsCompleted: 95,
  },
  {
    id: '6',
    name: 'Vijay Yadav',
    skill: 'General Labor',
    rate: 600,
    avatar: 'https://placehold.co/400x400.png',
    description: 'Hardworking and reliable for any general tasks like lifting, cleaning, and assistance.',
    rating: 4.5,
    jobsCompleted: 300,
  },
  {
    id: '7',
    name: 'Sunil Gupta',
    skill: 'Plumber',
    rate: 850,
    avatar: 'https://placehold.co/400x400.png',
    description: 'Specializes in fixing leakages and new pipe installations. Available on short notice.',
    rating: 4.7,
    jobsCompleted: 130,
  },
  {
    id: '8',
    name: 'Anil Chauhan',
    skill: 'Electrician',
    rate: 950,
    avatar: 'https://placehold.co/400x400.png',
    description: 'Experienced in handling complex electrical systems and ensuring everything is up to code.',
    rating: 4.9,
    jobsCompleted: 190,
  },
];
